sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor
    - $HOME/.local

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env:
        - DEPS=lowest
    - php: 7.0
      env:
        - EXECUTE_CS_CHECK=true
        - EXECUTE_TEST_SCRUTINIZER=true
        - DEPS=locked
    - php: 7.0
      env:
        - DEPS=latest
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=locked
    - php: 7.1
      env:
        - DEPS=latest
    - php: nightly
      env:
        - DEPS=lowest
    - php: nightly
      env:
        - DEPS=locked
    - php: nightly
      env:
        - DEPS=latest
  allow_failures:
    - php: nightly

before_install:
  - if [[ $EXECUTE_TEST_SCRUTINIZER != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update

install:
  - travis_retry composer install $COMPOSER_ARGS
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - composer show

script:
  - if [[ $EXECUTE_TEST_SCRUTINIZER == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover coverage.clover ; fi
  - if [[ $EXECUTE_TEST_SCRUTINIZER != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer cs-check ; fi

after_script:
  - if [[ $EXECUTE_TEST_SCRUTINIZER == 'true' ]]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ $EXECUTE_TEST_SCRUTINIZER == 'true' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover ; fi
